---

- name: awx playbook | update
  hosts: all
  gather_facts: True

  tasks:

  - block:

    - name: yum | update
      become: True
      yum:
        name: '*'
        state: latest
    when: ansible_os_family == "RedHat"

  - block:
    - name: apt | update
      become: True
      apt:
        upgrade: dist
        update_cache: yes
        cache_valid_time: 3600
    when: ansible_os_family == "Debian"
